# Generated by Django 5.1.6 on 2025-02-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='payments',
            new_name='payments_status',
        ),
        migrations.AlterField(
            model_name='patients',
            name='conditions',
            field=models.CharField(choices=[('A', 'Ansiedade'), ('TAG', 'Transtoono de ansiedade generalizada'), ('TDAH', 'TDAH'), ('D', 'Depressão')], max_length=4),
        ),
    ]
