# Generated by Django 5.1.6 on 2025-02-14 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_rename_payments_patients_payments_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=255)),
                ('instrution', models.TextField()),
                ('frequence', models.CharField(choices=[('D', 'Diário'), ('1S', '1 vez por semana'), ('2S', '2 vezes por semana'), ('3S', '3 vezes por semana'), ('N', 'Ao necessiatr')], default='D', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='patients',
            name='conditions',
            field=models.CharField(choices=[('A', 'Ansiedade'), ('D', 'Depressão'), ('TDAH', 'TDAH'), ('TAG', 'Transtoono de ansiedade generalizada')], max_length=4),
        ),
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humor', models.PositiveIntegerField()),
                ('geral_register', models.TextField()),
                ('video', models.FileField(upload_to='video')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patients')),
                ('todo', models.ManyToManyField(to='patients.todos')),
            ],
        ),
    ]
