# Generated by Django 5.2.3 on 2025-06-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_todos_alter_patients_conditions_consult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='conditions',
            field=models.CharField(choices=[('A', 'Ansiedade'), ('TAG', 'Transtoono de ansiedade generalizada'), ('TDAH', 'TDAH'), ('D', 'Depressão')], max_length=4),
        ),
    ]
